/*

This script generates the transparency indicators from BPK

source :https://www.bpk.go.id/ihps
- first semester of 2019 was published in september 2019 - which contains 2018 numbers
- 2018 numbers were not known at the time of the election (April 2019)

*/

/*
ihps_i_2019_1571802711.pdf page 306 
WTP : Opini Wajar Tanpa Pengecualian (unqualified opinion)
WTP DPP : Opini Wajar Tanpa Pengecualian Dengan Paragraf Penjelas (unqualified opinion with modified wording)
WDP : Opini Wajar Dengan Pengecualian (qualified opinion)
TW : Opini Tidak Wajar (adverse opinion)
TMP : Pernyataan Menolak Memberikan Opini atau Tidak Menyatakan Pendapat (disclaimer opinion)
*/


*cd ""
import excel "${raw_data_dir}/bpk reports/2005-2009.xlsx", sheet("Sheet1") clear


rename D district
rename F  opinion2005
rename H   opinion2006
rename J   opinion2007
rename L   opinion2008
rename N  	opinion2009


drop if district==""
drop if strpos(district,"Prov.")!=0


drop if district=="Jumlah"

keep district opinion*


replace district="Kab. Batu Bara" if district=="Kab. Batubara"
replace district="Kab. Gunungkidul" if district=="Kab. Gunung Kidul"
replace district="Kab. Kepulauan Tanimbar (Maluku Tenggara Barat)" if district=="Kab. Maluku Tenggara Barat"
replace district="Kab. Mempawah" if district=="Kab. Pontianak"
replace district="Kota Baubau" if district=="Kota Bau-Bau"
replace district="Kota Gunungsitoli" if district=="Kota Gunung Sitoli"
replace district="Kota Pagar Alam" if district=="Kota Pagaralam"
replace district="Kota Palangka Raya" if district=="Kota Palangkaraya"
replace district="Kota Pare pare" if district=="Kota Pare-Pare"

replace district = subinstr(district,"Kab.","Kab. ",1) if substr(district,1,5)!="Kab. "



tempfile k09
save `k09'

import excel "${raw_data_dir}/bpk reports/2010-2014.xlsx", sheet("Sheet1") clear


rename D district
rename F opinion2010
rename H opinion2011
rename J opinion2012
rename L opinion2013
rename N opinion2014


drop if _n==1
drop if district==""
drop if strpos(district,"Prov.")!=0
drop if strpos(district,"Opini Tahun")!=0

keep district opinion*

replace district = subinstr(district,"Kab.","Kab. ",1) if substr(district,1,5)!="Kab. "


replace district="Kab. Batu Bara" if district=="Kab. Batubara"
replace district="Kab. Gunungkidul" if district=="Kab. Gunung Kidul"
replace district="Kab. Kepulauan Tanimbar (Maluku Tenggara Barat)" if district=="Kab. Maluku Tenggara Barat"
replace district="Kab. Lanny Jaya" if district=="Kab. La n ny Jaya"
replace district="Kab. Mempawah" if district=="Kab. Pontianak (Mempawah)"
replace district="Kota Gunungsitoli" if district=="Kota Gunung Sitoli"
replace district="Kota Pare pare" if district=="Kota Pare-Pare"

tempfile k14
save `k14'

import excel "${raw_data_dir}/bpk reports/2015-2018.xlsx", sheet("Sheet1") clear


rename D district
rename F opinion2014_alt 
rename H opinion2015 
rename J opinion2016
rename L opinion2017
rename N opinion2018



drop if _n==1
drop if district==""
drop if strpos(district,"Prov.")!=0

keep district opinion*


replace district = subinstr(district,"Kab.","Kab. ",1) if substr(district,1,5)!="Kab. "
replace district = "Kab. Mamuju Utara" if district=="Kab. Pasangkayu (Mamuju Utara)"

merge 1:1 district using `k09', gen(m09)

merge 1:1 district using `k14', gen(m14)


drop if m14==2


order district opinion*, alpha


foreach v of varlist opinion2005 - opinion2018 {

	replace `v'=subinstr(`v',"*","",.)

}



*save "${processed_data_dir}/bpk_reports.dta", replace

foreach v of varlist opinion* {
	replace `v'=strtrim(`v')
	replace `v'="3" if `v'=="TMP"
	replace `v'="2" if `v'=="TW"
	replace `v'="1" if `v'=="WDP"
	replace `v'="0" if `v'=="WTP"
	replace `v'="0.5" if `v'=="WTP-DPP"|`v'=="WTP DPP"
	tab `v'
}
destring opinion*, force replace

drop opinion2014
rename opinion2014_alt opinion2014 // newer data point

rename opinion* opinion_numeric*

gen kab_code = .
replace kab_code=1101 if district=="Kab. Simeulue"
replace kab_code=1102 if district=="Kab. Aceh Singkil"
replace kab_code=1103 if district=="Kab. Aceh Selatan"
replace kab_code=1104 if district=="Kab. Aceh Tenggara"
replace kab_code=1105 if district=="Kab. Aceh Timur"
replace kab_code=1106 if district=="Kab. Aceh Tengah"
replace kab_code=1107 if district=="Kab. Aceh Barat"
replace kab_code=1108 if district=="Kab. Aceh Besar"
replace kab_code=1109 if district=="Kab. Pidie"
replace kab_code=1110 if district=="Kab. Bireuen"
replace kab_code=1111 if district=="Kab. Aceh Utara"
replace kab_code=1112 if district=="Kab. Aceh Barat Daya"
replace kab_code=1113 if district=="Kab. Gayo Lues"
replace kab_code=1114 if district=="Kab. Aceh Tamiang"
replace kab_code=1115 if district=="Kab. Nagan Raya"
replace kab_code=1116 if district=="Kab. Aceh Jaya"
replace kab_code=1117 if district=="Kab. Bener Meriah"
replace kab_code=1118 if district=="Kab. Pidie Jaya"
replace kab_code=1171 if district=="Kota Banda Aceh"
replace kab_code=1172 if district=="Kota Sabang"
replace kab_code=1173 if district=="Kota Langsa"
replace kab_code=1174 if district=="Kota Lhokseumawe"
replace kab_code=1175 if district=="Kota Subulussalam"
replace kab_code=1201 if district=="Kab. Nias"
replace kab_code=1202 if district=="Kab. Mandailing Natal"
replace kab_code=1203 if district=="Kab. Tapanuli Selatan"
replace kab_code=1204 if district=="Kab. Tapanuli Tengah"
replace kab_code=1205 if district=="Kab. Tapanuli Utara"
replace kab_code=1206 if district=="Kab. Toba Samosir"
replace kab_code=1207 if district=="Kab. Labuhanbatu"
replace kab_code=1208 if district=="Kab. Asahan"
replace kab_code=1209 if district=="Kab. Simalungun"
replace kab_code=1210 if district=="Kab. Dairi"
replace kab_code=1211 if district=="Kab. Karo"
replace kab_code=1212 if district=="Kab. Deli Serdang"
replace kab_code=1213 if district=="Kab. Langkat"
replace kab_code=1214 if district=="Kab. Nias Selatan"
replace kab_code=1215 if district=="Kab. Humbang Hasundutan"
replace kab_code=1216 if district=="Kab. Pakpak Bharat"
replace kab_code=1217 if district=="Kab. Samosir"
replace kab_code=1218 if district=="Kab. Serdang Bedagai"
replace kab_code=1219 if district=="Kab. Batu Bara"
replace kab_code=1220 if district=="Kab. Padang Lawas Utara"
replace kab_code=1221 if district=="Kab. Padang Lawas"
replace kab_code=1222 if district=="Kab. Labuhanbatu Selatan"
replace kab_code=1223 if district=="Kab. Labuhanbatu Utara"
replace kab_code=1224 if district=="Kab. Nias Utara"
replace kab_code=1225 if district=="Kab. Nias Barat"
replace kab_code=1271 if district=="Kota Sibolga"
replace kab_code=1272 if district=="Kota Tanjungbalai"
replace kab_code=1273 if district=="Kota Pematangsiantar"
replace kab_code=1274 if district=="Kota Tebing Tinggi"
replace kab_code=1275 if district=="Kota Medan"
replace kab_code=1276 if district=="Kota Binjai"
replace kab_code=1277 if district=="Kota Padangsidimpuan"
replace kab_code=1278 if district=="Kota Gunungsitoli"
replace kab_code=1301 if district=="Kab. Kep. Mentawai"
replace kab_code=1302 if district=="Kab. Pesisir Selatan"
replace kab_code=1303 if district=="Kab. Solok"
replace kab_code=1304 if district=="Kab. Sijunjung"
replace kab_code=1305 if district=="Kab. Tanah Datar"
replace kab_code=1306 if district=="Kab. Padang Pariaman"
replace kab_code=1307 if district=="Kab. Agam"
replace kab_code=1308 if district=="Kab. Lima Puluh Kota"
replace kab_code=1309 if district=="Kab. Pasaman"
replace kab_code=1310 if district=="Kab. Solok Selatan"
replace kab_code=1311 if district=="Kab. Dharmasraya"
replace kab_code=1312 if district=="Kab. Pasaman Barat"
replace kab_code=1371 if district=="Kota Padang"
replace kab_code=1372 if district=="Kota Solok"
replace kab_code=1373 if district=="Kota Sawahlunto"
replace kab_code=1374 if district=="Kota Padang Panjang"
replace kab_code=1375 if district=="Kota Bukittinggi"
replace kab_code=1376 if district=="Kota Payakumbuh"
replace kab_code=1377 if district=="Kota Pariaman"
replace kab_code=1401 if district=="Kab. Kuantan Singingi"
replace kab_code=1402 if district=="Kab. Indragiri Hulu"
replace kab_code=1403 if district=="Kab. Indragiri Hilir"
replace kab_code=1404 if district=="Kab. Pelalawan"
replace kab_code=1405 if district=="Kab. Siak"
replace kab_code=1406 if district=="Kab. Kampar"
replace kab_code=1407 if district=="Kab. Rokan Hulu"
replace kab_code=1408 if district=="Kab. Bengkalis"
replace kab_code=1409 if district=="Kab. Rokan Hilir"
replace kab_code=1410 if district=="Kab. Kepulauan Meranti"
replace kab_code=1471 if district=="Kota Pekanbaru"
replace kab_code=1473 if district=="Kota Dumai"
replace kab_code=1501 if district=="Kab. Kerinci"
replace kab_code=1502 if district=="Kab. Merangin"
replace kab_code=1503 if district=="Kab. Sarolangun"
replace kab_code=1504 if district=="Kab. Batang Hari"
replace kab_code=1505 if district=="Kab. Muaro Jambi"
replace kab_code=1506 if district=="Kab. Tanjung Jabung Timur"
replace kab_code=1507 if district=="Kab. Tanjung Jabung Barat"
replace kab_code=1508 if district=="Kab. Tebo"
replace kab_code=1509 if district=="Kab. Bungo"
replace kab_code=1571 if district=="Kota Jambi"
replace kab_code=1572 if district=="Kota Sungai Penuh"
replace kab_code=1601 if district=="Kab. Ogan Komering Ulu"
replace kab_code=1602 if district=="Kab. Ogan Komering Ilir"
replace kab_code=1603 if district=="Kab. Muara Enim"
replace kab_code=1604 if district=="Kab. Lahat"
replace kab_code=1605 if district=="Kab. Musi Rawas"
replace kab_code=1606 if district=="Kab. Musi Banyuasin"
replace kab_code=1607 if district=="Kab. Banyuasin"
replace kab_code=1608 if district=="Kab. Ogan Komering Ulu Selatan"
replace kab_code=1609 if district=="Kab. Ogan Komering Ulu Timur"
replace kab_code=1610 if district=="Kab. Ogan Ilir"
replace kab_code=1611 if district=="Kab. Empat Lawang"
replace kab_code=1612 if district=="Kab. Penukal Abab Lematang Ilir"
replace kab_code=1613 if district=="Kab. Musi Rawas Utara"
replace kab_code=1671 if district=="Kota Palembang"
replace kab_code=1672 if district=="Kota Prabumulih"
replace kab_code=1673 if district=="Kota Pagar Alam"
replace kab_code=1674 if district=="Kota Lubuklinggau"
replace kab_code=1701 if district=="Kab. Bengkulu Selatan"
replace kab_code=1702 if district=="Kab. Rejang Lebong"
replace kab_code=1703 if district=="Kab. Bengkulu Utara"
replace kab_code=1704 if district=="Kab. Kaur"
replace kab_code=1705 if district=="Kab. Seluma"
replace kab_code=1706 if district=="Kab. Mukomuko"
replace kab_code=1707 if district=="Kab. Lebong"
replace kab_code=1708 if district=="Kab. Kepahiang"
replace kab_code=1709 if district=="Kab. Bengkulu Tengah"
replace kab_code=1771 if district=="Kota Bengkulu"
replace kab_code=1801 if district=="Kab. Lampung Barat"
replace kab_code=1802 if district=="Kab. Tanggamus"
replace kab_code=1803 if district=="Kab. Lampung Selatan"
replace kab_code=1804 if district=="Kab. Lampung Timur"
replace kab_code=1805 if district=="Kab. Lampung Tengah"
replace kab_code=1806 if district=="Kab. Lampung Utara"
replace kab_code=1807 if district=="Kab. Way Kanan"
replace kab_code=1808 if district=="Kab. Tulang Bawang"
replace kab_code=1809 if district=="Kab. Pesawaran"
replace kab_code=1810 if district=="Kab. Pringsewu"
replace kab_code=1811 if district=="Kab. Mesuji"
replace kab_code=1812 if district=="Kab. Tulang Bawang Barat"
replace kab_code=1813 if district=="Kab. Pesisir Barat"
replace kab_code=1871 if district=="Kota Bandar Lampung"
replace kab_code=1872 if district=="Kota Metro"
replace kab_code=1901 if district=="Kab. Bangka"
replace kab_code=1902 if district=="Kab. Belitung"
replace kab_code=1903 if district=="Kab. Bangka Barat"
replace kab_code=1904 if district=="Kab. Bangka Tengah"
replace kab_code=1905 if district=="Kab. Bangka Selatan"
replace kab_code=1906 if district=="Kab. Belitung Timur"
replace kab_code=1971 if district=="Kota Pangkalpinang"
replace kab_code=2101 if district=="Kab. Karimun"
replace kab_code=2102 if district=="Kab. Bintan"
replace kab_code=2104 if district=="Kab. Lingga"
replace kab_code=2171 if district=="Kota Batam"
replace kab_code=2172 if district=="Kota Tanjungpinang"
replace kab_code=2103 if district=="Kab. Natuna"
replace kab_code=2105 if district=="Kab. Kepulauan Anambas"
replace kab_code=3201 if district=="Kab. Bogor"
replace kab_code=3202 if district=="Kab. Sukabumi"
replace kab_code=3203 if district=="Kab. Cianjur"
replace kab_code=3204 if district=="Kab. Bandung"
replace kab_code=3205 if district=="Kab. Garut"
replace kab_code=3206 if district=="Kab. Tasikmalaya"
replace kab_code=3207 if district=="Kab. Ciamis"
replace kab_code=3208 if district=="Kab. Kuningan"
replace kab_code=3209 if district=="Kab. Cirebon"
replace kab_code=3210 if district=="Kab. Majalengka"
replace kab_code=3211 if district=="Kab. Sumedang"
replace kab_code=3212 if district=="Kab. Indramayu"
replace kab_code=3213 if district=="Kab. Subang"
replace kab_code=3214 if district=="Kab. Purwakarta"
replace kab_code=3215 if district=="Kab. Karawang"
replace kab_code=3216 if district=="Kab. Bekasi"
replace kab_code=3217 if district=="Kab. Bandung Barat"
replace kab_code=3218 if district=="Kab. Pangandaran"
replace kab_code=3271 if district=="Kota Bogor"
replace kab_code=3272 if district=="Kota Sukabumi"
replace kab_code=3273 if district=="Kota Bandung"
replace kab_code=3274 if district=="Kota Cirebon"
replace kab_code=3275 if district=="Kota Bekasi"
replace kab_code=3276 if district=="Kota Depok"
replace kab_code=3277 if district=="Kota Cimahi"
replace kab_code=3278 if district=="Kota Tasikmalaya"
replace kab_code=3279 if district=="Kota Banjar"
replace kab_code=3301 if district=="Kab. Cilacap"
replace kab_code=3302 if district=="Kab. Banyumas"
replace kab_code=3303 if district=="Kab. Purbalingga"
replace kab_code=3304 if district=="Kab. Banjarnegara"
replace kab_code=3305 if district=="Kab. Kebumen"
replace kab_code=3306 if district=="Kab. Purworejo"
replace kab_code=3307 if district=="Kab. Wonosobo"
replace kab_code=3308 if district=="Kab. Magelang"
replace kab_code=3309 if district=="Kab. Boyolali"
replace kab_code=3310 if district=="Kab. Klaten"
replace kab_code=3311 if district=="Kab. Sukoharjo"
replace kab_code=3312 if district=="Kab. Wonogiri"
replace kab_code=3313 if district=="Kab. Karanganyar"
replace kab_code=3314 if district=="Kab. Sragen"
replace kab_code=3315 if district=="Kab. Grobogan"
replace kab_code=3316 if district=="Kab. Blora"
replace kab_code=3317 if district=="Kab. Rembang"
replace kab_code=3318 if district=="Kab. Pati"
replace kab_code=3319 if district=="Kab. Kudus"
replace kab_code=3320 if district=="Kab. Jepara"
replace kab_code=3321 if district=="Kab. Demak"
replace kab_code=3322 if district=="Kab. Semarang"
replace kab_code=3323 if district=="Kab. Temanggung"
replace kab_code=3324 if district=="Kab. Kendal"
replace kab_code=3325 if district=="Kab. Batang"
replace kab_code=3326 if district=="Kab. Pekalongan"
replace kab_code=3327 if district=="Kab. Pemalang"
replace kab_code=3328 if district=="Kab. Tegal"
replace kab_code=3329 if district=="Kab. Brebes"
replace kab_code=3371 if district=="Kota Magelang"
replace kab_code=3372 if district=="Kota Surakarta"
replace kab_code=3373 if district=="Kota Salatiga"
replace kab_code=3374 if district=="Kota Semarang"
replace kab_code=3375 if district=="Kota Pekalongan"
replace kab_code=3376 if district=="Kota Tegal"
replace kab_code=3401 if district=="Kab. Kulon Progo"
replace kab_code=3402 if district=="Kab. Bantul"
replace kab_code=3403 if district=="Kab. Gunungkidul"
replace kab_code=3404 if district=="Kab. Sleman"
replace kab_code=3471 if district=="Kota Yogyakarta"
replace kab_code=3501 if district=="Kab. Pacitan"
replace kab_code=3502 if district=="Kab. Ponorogo"
replace kab_code=3503 if district=="Kab. Trenggalek"
replace kab_code=3504 if district=="Kab. Tulungagung"
replace kab_code=3505 if district=="Kab. Blitar"
replace kab_code=3506 if district=="Kab. Kediri"
replace kab_code=3507 if district=="Kab. Malang"
replace kab_code=3508 if district=="Kab. Lumajang"
replace kab_code=3509 if district=="Kab. Jember"
replace kab_code=3510 if district=="Kab. Banyuwangi"
replace kab_code=3511 if district=="Kab. Bondowoso"
replace kab_code=3512 if district=="Kab. Situbondo"
replace kab_code=3513 if district=="Kab. Probolinggo"
replace kab_code=3514 if district=="Kab. Pasuruan"
replace kab_code=3515 if district=="Kab. Sidoarjo"
replace kab_code=3516 if district=="Kab. Mojokerto"
replace kab_code=3517 if district=="Kab. Jombang"
replace kab_code=3518 if district=="Kab. Nganjuk"
replace kab_code=3519 if district=="Kab. Madiun"
replace kab_code=3520 if district=="Kab. Magetan"
replace kab_code=3521 if district=="Kab. Ngawi"
replace kab_code=3522 if district=="Kab. Bojonegoro"
replace kab_code=3523 if district=="Kab. Tuban"
replace kab_code=3524 if district=="Kab. Lamongan"
replace kab_code=3525 if district=="Kab. Gresik"
replace kab_code=3526 if district=="Kab. Bangkalan"
replace kab_code=3527 if district=="Kab. Sampang"
replace kab_code=3528 if district=="Kab. Pamekasan"
replace kab_code=3529 if district=="Kab. Sumenep"
replace kab_code=3571 if district=="Kota Kediri"
replace kab_code=3572 if district=="Kota Blitar"
replace kab_code=3573 if district=="Kota Malang"
replace kab_code=3574 if district=="Kota Probolinggo"
replace kab_code=3575 if district=="Kota Pasuruan"
replace kab_code=3576 if district=="Kota Mojokerto"
replace kab_code=3577 if district=="Kota Madiun"
replace kab_code=3578 if district=="Kota Surabaya"
replace kab_code=3579 if district=="Kota Batu"
replace kab_code=3601 if district=="Kab. Pandeglang"
replace kab_code=3602 if district=="Kab. Lebak"
replace kab_code=3603 if district=="Kab. Tangerang"
replace kab_code=3604 if district=="Kab. Serang"
replace kab_code=3671 if district=="Kota Tangerang"
replace kab_code=3672 if district=="Kota Cilegon"
replace kab_code=3673 if district=="Kota Serang"
replace kab_code=3674 if district=="Kota Tangerang Selatan"
replace kab_code=5101 if district=="Kab. Jembrana"
replace kab_code=5102 if district=="Kab. Tabanan"
replace kab_code=5103 if district=="Kab. Badung"
replace kab_code=5104 if district=="Kab. Gianyar"
replace kab_code=5105 if district=="Kab. Klungkung"
replace kab_code=5106 if district=="Kab. Bangli"
replace kab_code=5107 if district=="Kab. Karangasem"
replace kab_code=5108 if district=="Kab. Buleleng"
replace kab_code=5171 if district=="Kota Denpasar"
replace kab_code=5201 if district=="Kab. Lombok Barat"
replace kab_code=5202 if district=="Kab. Lombok Tengah"
replace kab_code=5203 if district=="Kab. Lombok Timur"
replace kab_code=5204 if district=="Kab. Sumbawa"
replace kab_code=5205 if district=="Kab. Dompu"
replace kab_code=5206 if district=="Kab. Bima"
replace kab_code=5207 if district=="Kab. Sumbawa Barat"
replace kab_code=5208 if district=="Kab. Lombok Utara"
replace kab_code=5271 if district=="Kota Mataram"
replace kab_code=5272 if district=="Kota Bima"
replace kab_code=5301 if district=="Kab. Sumba Barat"
replace kab_code=5302 if district=="Kab. Sumba Timur"
replace kab_code=5303 if district=="Kab. Kupang"
replace kab_code=5304 if district=="Kab. Timor Tengah Selatan"
replace kab_code=5305 if district=="Kab. Timor Tengah Utara"
replace kab_code=5306 if district=="Kab. Belu"
replace kab_code=5307 if district=="Kab. Alor"
replace kab_code=5308 if district=="Kab. Lembata"
replace kab_code=5309 if district=="Kab. Flores Timur"
replace kab_code=5310 if district=="Kab. Sikka"
replace kab_code=5311 if district=="Kab. Ende"
replace kab_code=5312 if district=="Kab. Ngada"
replace kab_code=5313 if district=="Kab. Manggarai"
replace kab_code=5314 if district=="Kab. Rote Ndao"
replace kab_code=5315 if district=="Kab. Manggarai Barat"
replace kab_code=5316 if district=="Kab. Sumba Tengah"
replace kab_code=5317 if district=="Kab. Sumba Barat Daya"
replace kab_code=5318 if district=="Kab. Nagekeo"
replace kab_code=5319 if district=="Kab. Manggarai Timur"
replace kab_code=5320 if district=="Kab. Sabu Raijua"
replace kab_code=5321 if district=="Kab. Malaka"
replace kab_code=5371 if district=="Kota Kupang"
replace kab_code=6101 if district=="Kab. Sambas"
replace kab_code=6102 if district=="Kab. Bengkayang"
replace kab_code=6103 if district=="Kab. Landak"
replace kab_code=6104 if district=="Kab. Mempawah"
replace kab_code=6105 if district=="Kab. Sanggau"
replace kab_code=6106 if district=="Kab. Ketapang"
replace kab_code=6107 if district=="Kab. Sintang"
replace kab_code=6108 if district=="Kab. Kapuas Hulu"
replace kab_code=6109 if district=="Kab. Sekadau"
replace kab_code=6110 if district=="Kab. Melawi"
replace kab_code=6111 if district=="Kab. Kayong Utara"
replace kab_code=6112 if district=="Kab. Kubu Raya"
replace kab_code=6171 if district=="Kota Pontianak"
replace kab_code=6172 if district=="Kota Singkawang"
replace kab_code=6201 if district=="Kab. Kotawaringin Barat"
replace kab_code=6202 if district=="Kab. Kotawaringin Timur"
replace kab_code=6203 if district=="Kab. Kapuas"
replace kab_code=6204 if district=="Kab. Barito Selatan"
replace kab_code=6205 if district=="Kab. Barito Utara"
replace kab_code=6206 if district=="Kab. Sukamara"
replace kab_code=6207 if district=="Kab. Lamandau"
replace kab_code=6208 if district=="Kab. Seruyan"
replace kab_code=6209 if district=="Kab. Katingan"
replace kab_code=6210 if district=="Kab. Pulang Pisau"
replace kab_code=6211 if district=="Kab. Gunung Mas"
replace kab_code=6212 if district=="Kab. Barito Timur"
replace kab_code=6213 if district=="Kab. Murung Raya"
replace kab_code=6271 if district=="Kota Palangka Raya"
replace kab_code=6301 if district=="Kab. Tanah Laut"
replace kab_code=6302 if district=="Kab. Kotabaru"
replace kab_code=6303 if district=="Kab. Banjar"
replace kab_code=6304 if district=="Kab. Barito Kuala"
replace kab_code=6305 if district=="Kab. Tapin"
replace kab_code=6306 if district=="Kab. Hulu Sungai Selatan"
replace kab_code=6307 if district=="Kab. Hulu Sungai Tengah"
replace kab_code=6308 if district=="Kab. Hulu Sungai Utara"
replace kab_code=6309 if district=="Kab. Tabalong"
replace kab_code=6310 if district=="Kab. Tanah Bumbu"
replace kab_code=6311 if district=="Kab. Balangan"
replace kab_code=6371 if district=="Kota Banjarmasin"
replace kab_code=6372 if district=="Kota Banjarbaru"
replace kab_code=6401 if district=="Kab. Paser"
replace kab_code=6402 if district=="Kab. Kutai Barat"
replace kab_code=6403 if district=="Kab. Kutai Kartanegara"
replace kab_code=6404 if district=="Kab. Kutai Timur"
replace kab_code=6405 if district=="Kab. Berau"
replace kab_code=6501 if district=="Kab. Malinau"
replace kab_code=6502 if district=="Kab. Bulungan"
replace kab_code=6504 if district=="Kab. Nunukan"
replace kab_code=6409 if district=="Kab. Penajam Paser Utara"
replace kab_code=6411 if district=="Kab. Mahakam Ulu"
replace kab_code=6471 if district=="Kota Balikpapan"
replace kab_code=6472 if district=="Kota Samarinda"
replace kab_code=6571 if district=="Kota Tarakan"
replace kab_code=6474 if district=="Kota Bontang"
replace kab_code=7101 if district=="Kab. Bolaang Mongondow"
replace kab_code=7102 if district=="Kab. Minahasa"
replace kab_code=7103 if district=="Kab. Kepulauan Sangihe"
replace kab_code=7104 if district=="Kab. Kepulauan Talaud"
replace kab_code=7105 if district=="Kab. Minahasa Selatan"
replace kab_code=7106 if district=="Kab. Minahasa Utara"
replace kab_code=7107 if district=="Kab. Bolaang Mongondow Utara"
replace kab_code=7108 if district=="Kab. Kep. Siau Tagulandang Biaro"
replace kab_code=7109 if district=="Kab. Minahasa Tenggara"
replace kab_code=7110 if district=="Kab. Bolaang Mongondow Selatan"
replace kab_code=7111 if district=="Kab. Bolaang Mongondow Timur"
replace kab_code=7171 if district=="Kota Manado"
replace kab_code=7172 if district=="Kota Bitung"
replace kab_code=7173 if district=="Kota Tomohon"
replace kab_code=7174 if district=="Kota Kotamobagu"
replace kab_code=7201 if district=="Kab. Banggai Kepulauan"
replace kab_code=7202 if district=="Kab. Banggai"
replace kab_code=7203 if district=="Kab. Morowali"
replace kab_code=7204 if district=="Kab. Poso"
replace kab_code=7205 if district=="Kab. Donggala"
replace kab_code=7206 if district=="Kab. Tolitoli"
replace kab_code=7207 if district=="Kab. Buol"
replace kab_code=7208 if district=="Kab. Parigi Moutong"
replace kab_code=7209 if district=="Kab. Tojo Una-Una"
replace kab_code=7210 if district=="Kab. Sigi"
replace kab_code=7211 if district=="Kab. Banggai Laut"
replace kab_code=7212 if district=="Kab. Morowali Utara"
replace kab_code=7271 if district=="Kota Palu"
replace kab_code=7301 if district=="Kab. Kep. Selayar"
replace kab_code=7302 if district=="Kab. Bulukumba"
replace kab_code=7303 if district=="Kab. Bantaeng"
replace kab_code=7304 if district=="Kab. Jeneponto"
replace kab_code=7305 if district=="Kab. Takalar"
replace kab_code=7306 if district=="Kab. Gowa"
replace kab_code=7307 if district=="Kab. Sinjai"
replace kab_code=7308 if district=="Kab. Maros"
replace kab_code=7309 if district=="Kab. Pangkajene dan Kepulauan"
replace kab_code=7310 if district=="Kab. Barru"
replace kab_code=7311 if district=="Kab. Bone"
replace kab_code=7312 if district=="Kab. Soppeng"
replace kab_code=7313 if district=="Kab. Wajo"
replace kab_code=7314 if district=="Kab. Sidenreng Rappang"
replace kab_code=7315 if district=="Kab. Pinrang"
replace kab_code=7316 if district=="Kab. Enrekang"
replace kab_code=7317 if district=="Kab. Luwu"
replace kab_code=7318 if district=="Kab. Tana Toraja"
replace kab_code=7322 if district=="Kab. Luwu Utara"
replace kab_code=7325 if district=="Kab. Luwu Timur"
replace kab_code=7326 if district=="Kab. Toraja Utara"
replace kab_code=7371 if district=="Kota Makassar"
replace kab_code=7372 if district=="Kota Pare pare"
replace kab_code=7373 if district=="Kota Palopo"
replace kab_code=7401 if district=="Kab. Buton"
replace kab_code=7402 if district=="Kab. Muna"
replace kab_code=7403 if district=="Kab. Konawe"
replace kab_code=7404 if district=="Kab. Kolaka"
replace kab_code=7405 if district=="Kab. Konawe Selatan"
replace kab_code=7406 if district=="Kab. Bombana"
replace kab_code=7407 if district=="Kab. Wakatobi"
replace kab_code=7408 if district=="Kab. Kolaka Utara"
replace kab_code=7409 if district=="Kab. Buton Utara"
replace kab_code=7410 if district=="Kab. Konawe Utara"
replace kab_code=7411 if district=="Kab. Kolaka Timur"
replace kab_code=7412 if district=="Kab. Konawe Kepulauan"
replace kab_code=7413 if district=="Kab. Muna Barat"
replace kab_code=7414 if district=="Kab. Buton Tengah"
replace kab_code=7415 if district=="Kab. Buton Selatan"
replace kab_code=7471 if district=="Kota Kendari"
replace kab_code=7472 if district=="Kota Baubau"
replace kab_code=7501 if district=="Kab. Boalemo"
replace kab_code=7502 if district=="Kab. Gorontalo"
replace kab_code=7503 if district=="Kab. Pohuwato"
replace kab_code=7504 if district=="Kab. Bone Bolango"
replace kab_code=7505 if district=="Kab. Gorontalo Utara"
replace kab_code=7571 if district=="Kota Gorontalo"
replace kab_code=7601 if district=="Kab. Majene"
replace kab_code=7602 if district=="Kab. Polewali Mandar"
replace kab_code=7603 if district=="Kab. Mamasa"
replace kab_code=7604 if district=="Kab. Mamuju"
replace kab_code=7605 if district=="Kab. Mamuju Utara"
replace kab_code=7606 if district=="Kab. Mamuju Tengah"
replace kab_code=8101 if district=="Kab. Kepulauan Tanimbar (Maluku Tenggara Barat)"
replace kab_code=8102 if district=="Kab. Maluku Tenggara"
replace kab_code=8103 if district=="Kab. Maluku Tengah"
replace kab_code=8104 if district=="Kab. Buru"
replace kab_code=8105 if district=="Kab. Kepulauan Aru"
replace kab_code=8106 if district=="Kab. Seram Bagian Barat"
replace kab_code=8107 if district=="Kab. Seram Bagian Timur"
replace kab_code=8108 if district=="Kab. Maluku Barat Daya"
replace kab_code=8109 if district=="Kab. Buru Selatan"
replace kab_code=8171 if district=="Kota Ambon"
replace kab_code=8172 if district=="Kota Tual"
replace kab_code=8201 if district=="Kab. Halmahera Barat"
replace kab_code=8202 if district=="Kab. Halmahera Tengah"
replace kab_code=8203 if district=="Kab. Kepulauan Sula"
replace kab_code=8204 if district=="Kab. Halmahera Selatan"
replace kab_code=8205 if district=="Kab. Halmahera Utara"
replace kab_code=8206 if district=="Kab. Halmahera Timur"
replace kab_code=8207 if district=="Kab. Pulau Morotai"
replace kab_code=8208 if district=="Kab. Pulau Taliabu"
replace kab_code=8271 if district=="Kota Ternate"
replace kab_code=8272 if district=="Kota Tidore Kepulauan"
replace kab_code=9101 if district=="Kab. Fakfak"
replace kab_code=9102 if district=="Kab. Kaimana"
replace kab_code=9103 if district=="Kab. Teluk Wondama"
replace kab_code=9104 if district=="Kab. Teluk Bintuni"
replace kab_code=9105 if district=="Kab. Manokwari"
replace kab_code=9106 if district=="Kab. Sorong Selatan"
replace kab_code=9107 if district=="Kab. Sorong"
replace kab_code=9108 if district=="Kab. Raja Ampat"
replace kab_code=9109 if district=="Kab. Tambrauw"
replace kab_code=9110 if district=="Kab. Maybrat"
replace kab_code=9111 if district=="Kab. Manokwari Selatan"
replace kab_code=9112 if district=="Kab. Pegunungan Arfak"
replace kab_code=9171 if district=="Kota Sorong"
replace kab_code=9401 if district=="Kab. Merauke"
replace kab_code=9402 if district=="Kab. Jayawijaya"
replace kab_code=9403 if district=="Kab. Jayapura"
replace kab_code=9404 if district=="Kab. Nabire"
replace kab_code=9408 if district=="Kab. Kepulauan Yapen"
replace kab_code=9409 if district=="Kab. Biak Numfor"
replace kab_code=9410 if district=="Kab. Paniai"
replace kab_code=9411 if district=="Kab. Puncak Jaya"
replace kab_code=9412 if district=="Kab. Mimika"
replace kab_code=9413 if district=="Kab. Boven Digoel"
replace kab_code=9414 if district=="Kab. Mappi"
replace kab_code=9415 if district=="Kab. Asmat"
replace kab_code=9416 if district=="Kab. Yahukimo"
replace kab_code=9417 if district=="Kab. Pegunungan Bintang"
replace kab_code=9418 if district=="Kab. Tolikara"
replace kab_code=9419 if district=="Kab. Sarmi"
replace kab_code=9420 if district=="Kab. Keerom"
replace kab_code=9426 if district=="Kab. Waropen"
replace kab_code=9427 if district=="Kab. Supiori"
replace kab_code=9428 if district=="Kab. Mamberamo Raya"
replace kab_code=9429 if district=="Kab. Nduga"
replace kab_code=9430 if district=="Kab. Lanny Jaya"
replace kab_code=9431 if district=="Kab. Mamberamo Tengah"
replace kab_code=9432 if district=="Kab. Yalimo"
replace kab_code=9433 if district=="Kab. Puncak"
replace kab_code=9434 if district=="Kab. Dogiyai"
replace kab_code=9435 if district=="Kab. Intan Jaya"
replace kab_code=9436 if district=="Kab. Deiyai"
replace kab_code=9471 if district=="Kota Jayapura"
replace kab_code=6503 if district=="Kab. Tana Tidung"



save ${processed_data_dir}/transparency_indicators_wide.dta, replace
